"""remove dummy feature

Revision ID: 0c8d0c1a70e2
Revises: facaca31553e
Create Date: 2026-07-07 10:31:56.621604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8d0c1a70e2'
down_revision: Union[str, None] = 'facaca31553e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dummy_feature')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_feature', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
