"""add expense status

Revision ID: 2e2eb1027130
Revises: caf783349d82
Create Date: 2026-07-12 10:08:14.074583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2eb1027130'
down_revision: Union[str, None] = 'caf783349d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_products_barcode', ['barcode'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_barcode', type_='unique')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
