"""add suggested_product_id to appointments

Revision ID: 3e80ee1b89a8
Revises: 2e2eb1027130
Create Date: 2026-07-12 11:14:08.467010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e80ee1b89a8'
down_revision: Union[str, None] = '2e2eb1027130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_product_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_appointments_suggested_product_id', 'products', ['suggested_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_suggested_product_id', type_='foreignkey')
        batch_op.drop_column('suggested_product_id')

    # ### end Alembic commands ###
