"""add created_by to centers

Revision ID: 6415485837af
Revises: 4a487ed2abee
Create Date: 2026-07-05 12:17:46.882132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6415485837af'
down_revision: Union[str, None] = '4a487ed2abee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_centers_created_by', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
