"""Add reference_code and system_counters

Revision ID: 87ce2b8ac108
Revises: 7f6e5d4c3b2a
Create Date: 2026-08-30 14:39:14.095276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ce2b8ac108'
down_revision: Union[str, None] = '7f6e5d4c3b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_counters',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointments_reference_code'), ['reference_code'], unique=True)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_code', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_visits_reference_code'), ['reference_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_reference_code'))
        batch_op.drop_column('reference_code')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_reference_code'))
        batch_op.drop_column('reference_code')
        
    op.drop_table('system_counters')
    # ### end Alembic commands ###
