"""make brand_id NOT NULL on centers and products

Revision ID: a65f890c5203
Revises: 7c0af61b59ff
Create Date: 2026-07-22 09:45:44.651644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65f890c5203'
down_revision: Union[str, None] = '7c0af61b59ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('centers', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
