"""Add SpecialRequest, update Expense, Visit, and Appointment

Revision ID: d2d980bb5e7f
Revises: d5e6f7a8b9c0
Create Date: 2026-07-14 14:37:05.590278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d980bb5e7f'
down_revision: Union[str, None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_requests',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('visit_id', sa.String(), nullable=False),
        sa.Column('request_type', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_note', sa.String(), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_admin_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('visit_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key('fk_expenses_approved_by_users', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('pharmacy_stock_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competitor_product_name', sa.String(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_note', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('retroactive_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('save_location_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('save_location_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('save_location_lng')
        batch_op.drop_column('save_location_lat')
        batch_op.drop_column('retroactive_reason')
        batch_op.drop_column('supervisor_note')

    with op.batch_alter_table('pharmacy_stock_checks', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('competitor_product_name')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('visit_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('requires_admin_approval')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('supervisor_note')

    op.drop_table('special_requests')
    # ### end Alembic commands ###
