"""add client_id to visits

Revision ID: e754cb421f26
Revises: a2b3c4d5e6f7
Create Date: 2026-07-15 14:46:03.310621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e754cb421f26'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(), nullable=True))
        batch_op.alter_column('center_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key('fk_visits_client_id_clients', 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_visits_client_id_clients', type_='foreignkey')
        batch_op.alter_column('center_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
