"""add barcode to products

Revision ID: ef162eed15d3
Revises: 3e80ee1b89a8
Create Date: 2026-07-12 12:05:16.457951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef162eed15d3'
down_revision: Union[str, None] = '3e80ee1b89a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(), nullable=True))
    op.create_unique_constraint('uq_products_barcode', 'products', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_barcode', 'products', type_='unique')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
