"""add dummy feature

Revision ID: facaca31553e
Revises: ceaf9e290263
Create Date: 2026-07-07 10:30:52.063082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facaca31553e'
down_revision: Union[str, None] = 'ceaf9e290263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_feature', sa.String(), nullable=True))
        batch_op.drop_column('test_col')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_col', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('dummy_feature')

    # ### end Alembic commands ###
